name: Detect Secrets Scanner
description: Scan for VERIFIED hardcoded secrets and upload to GitHub Code Scanning.
inputs:
  scan-path:
    description: Directory to scan for secrets (e.g., ./src/.aws-sam/build)
    required: false
    default: .
  upload-sarif:
    description: Upload SARIF results to GitHub Code Scanning
    required: false
    default: 'false'
  fail-on-detection:
    description: Fail workflow if verified secrets detected
    required: false
    default: 'true'
  debug-mode:
    description: Enable verbose diagnostic logging
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Debug Context
      if: ${{ inputs.debug-mode == 'true' }}
      shell: bash
      run: |
        echo "::group::Debug Info"
        echo "Scan Path: ${{ inputs.scan-path }}"
        echo "SHA: $GITHUB_SHA"
        echo "python3: $(python3 --version)"
        echo "jq: $(jq --version)"
        echo "::endgroup::"

    - name: Install detect-secrets
      shell: bash
      run: |
        set -euo pipefail
        python3 -m pip install --upgrade pip --quiet
        pip install detect-secrets --quiet

    - name: Scan for verified secrets
      id: secret-scan
      shell: bash
      env:
        SCAN_PATH: ${{ inputs.scan-path }}
        DEBUG_MODE: ${{ inputs.debug-mode }}
      run: |
        set -euo pipefail

        # Validate scan path exists
        if [[ ! -e "${SCAN_PATH}" ]]; then
          echo "::error::Scan path '${SCAN_PATH}' does not exist"
          exit 1
        fi

        echo "::group::Scanning for verified secrets"
        if [[ "${DEBUG_MODE}" == "true" ]]; then
          echo "Command: detect-secrets scan ${SCAN_PATH} --all-files --only-verified"
        fi

        # Scan for VERIFIED secrets only - live credentials
        # --all-files: Scan all files including untracked/gitignored (e.g., build artifacts)
        # --only-verified: Only return secrets that can be verified (network calls to check if valid)
        detect-secrets scan "${SCAN_PATH}" --all-files --only-verified > detect-secrets-output.json
        echo "::endgroup::"

        # Count verified secrets found
        VERIFIED_COUNT=$(jq -r '(.results? // {}) | [.[] | length] | add // 0' detect-secrets-output.json)

        echo "verified_count=${VERIFIED_COUNT}" >> "${GITHUB_OUTPUT}"
        echo "Found ${VERIFIED_COUNT} verified secret(s)"

        # Handle results
        if [[ ${VERIFIED_COUNT} -gt 0 ]]; then
          # Convert to SARIF
          jq \
            --arg repoUri "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
            --arg revision "${GITHUB_SHA}" \
            --arg branch "${GITHUB_REF_NAME}" \
            -f "${{ github.action_path }}/detect-secrets-to-sarif.jq" \
            detect-secrets-output.json > detect-secrets-results.sarif

          # Mark for failure
          if [[ "${{ inputs.fail-on-detection }}" == "true" ]]; then
            echo "fail_after_upload=true" >> "${GITHUB_OUTPUT}"
            echo "::error::Found ${VERIFIED_COUNT} verified secret(s) - these are LIVE credentials!"
          else
            echo "::warning::Found ${VERIFIED_COUNT} verified secret(s)"
          fi

          if [[ "${DEBUG_MODE}" == "true" ]]; then
            echo "::group::SARIF Preview"
            head -n 25 detect-secrets-results.sarif
            echo "::endgroup::"
          fi
        else
          echo "::notice::No verified secrets detected"
        fi

    - name: Upload SARIF to GitHub Code Scanning
      if: ${{ inputs.upload-sarif == 'true' && steps.secret-scan.outputs.verified_count > 0 }}
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: detect-secrets-results.sarif
        category: detect-secrets

    - name: SARIF Artifact (debug only)
      if: ${{ inputs.debug-mode == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: detect-secrets-sarif
        path: detect-secrets-results.sarif
        retention-days: 5

    - name: Fail if secrets were detected
      if: ${{ steps.secret-scan.outputs.fail_after_upload == 'true' }}
      shell: bash
      run: |
        echo "Failing build due to detected secrets."
        exit 1